### ISSUE TITLE
Converter from Web Demonstrator broken

### ISSUE THREAD

**Issue by ryou90** [jmccrae/gwn-scala-api#13]
Hi,
looks like the Converter at https://server1.nlp.insight-centre.org/gwn-converter/ is broken. Every time i try to upload one wordnet file and to convert this to RDF ntriples, the application crashes. Also tried only little test input data, but also crashes..

**Comment by jmccrae** [comment]
Appears to be a compile issue

```
java.lang.UnsupportedClassVersionError: eu/monnetproject/lang/Language
	at org.globalwordnet.api.serialize.WNLMF.readLexicon(xml.scala:150)
	at org.globalwordnet.api.serialize.WNLMF.$anonfun$readLexicalResource$1(xml.scala:132)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.globalwordnet.api.serialize.WNLMF.readLexicalResource(xml.scala:132)
	at org.globalwordnet.api.serialize.WNLMF.read(xml.scala:128)
	at org.globalwordnet.api.web.GWNConverter.$anonfun$convert$1(GWNConverter.scala:129)
```

**Comment by jmccrae** [comment]
Fix is to update Tomcat version in the `Dockerfile`

Fixed in `docker` branch and change does not need to be merged into `master`
